<?php

namespace ContainerD9dPBDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CRM1lY4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cRM1lY4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cRM1lY4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'collecte' => ['privates', '.errored..service_locator.cRM1lY4.App\\Entity\\Collecte', NULL, 'Cannot autowire service ".service_locator.cRM1lY4": it needs an instance of "App\\Entity\\Collecte" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'collecte' => 'App\\Entity\\Collecte',
            'entityManager' => '?',
        ]);
    }
}
