<?php

namespace ContainerD9dPBDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FZv9eWNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FZv9eWN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FZv9eWN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'role' => ['privates', '.errored..service_locator.FZv9eWN.App\\Entity\\Role', NULL, 'Cannot autowire service ".service_locator.FZv9eWN": it needs an instance of "App\\Entity\\Role" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'role' => 'App\\Entity\\Role',
        ]);
    }
}
