<?php

namespace ContainerD9dPBDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RvSyk07Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rvSyk07' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rvSyk07'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phaseRepository' => ['privates', 'App\\Repository\\PhaseRepository', 'getPhaseRepositoryService', true],
            'plannigRepository' => ['privates', 'App\\Repository\\PlannigRepository', 'getPlannigRepositoryService', true],
        ], [
            'phaseRepository' => 'App\\Repository\\PhaseRepository',
            'plannigRepository' => 'App\\Repository\\PlannigRepository',
        ]);
    }
}
