<?php

namespace ContainerD9dPBDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BAdYLWcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BAdYLWc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BAdYLWc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produitsBoutique' => ['privates', '.errored..service_locator.BAdYLWc.App\\Entity\\ProduitsBoutique', NULL, 'Cannot autowire service ".service_locator.BAdYLWc": it needs an instance of "App\\Entity\\ProduitsBoutique" but this type has been excluded in "config/services.yaml".'],
        ], [
            'produitsBoutique' => 'App\\Entity\\ProduitsBoutique',
        ]);
    }
}
