<?php

namespace ContainerD9dPBDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCollecte2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cRM1lY4.App\Entity\Collecte' shared service.
     *
     * @return \App\Entity\Collecte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cRM1lY4": it needs an instance of "App\\Entity\\Collecte" but this type has been excluded in "config/services.yaml".');
    }
}
