<?php

namespace ContainerD9dPBDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivraisonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XA7Hpe0.App\Entity\Livraison' shared service.
     *
     * @return \App\Entity\Livraison
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XA7Hpe0": it needs an instance of "App\\Entity\\Livraison" but this type has been excluded in "config/services.yaml".');
    }
}
