<?php

namespace ContainerD9dPBDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRole2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NjZv6sH.App\Entity\Role' shared service.
     *
     * @return \App\Entity\Role
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NjZv6sH": it needs an instance of "App\\Entity\\Role" but this type has been excluded in "config/services.yaml".');
    }
}
