<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NUlWDAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NUlW_DA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NUlW_DA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'collecte' => ['privates', '.errored..service_locator.NUlW_DA.App\\Entity\\Collecte', NULL, 'Cannot autowire service ".service_locator.NUlW_DA": it needs an instance of "App\\Entity\\Collecte" but this type has been excluded in "config/services.yaml".'],
        ], [
            'collecte' => 'App\\Entity\\Collecte',
        ]);
    }
}
