<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VLYgdnAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VLYgdnA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VLYgdnA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produitsBoutique' => ['privates', '.errored..service_locator.VLYgdnA.App\\Entity\\ProduitsBoutique', NULL, 'Cannot autowire service ".service_locator.VLYgdnA": it needs an instance of "App\\Entity\\ProduitsBoutique" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'produitsBoutique' => 'App\\Entity\\ProduitsBoutique',
        ]);
    }
}
