<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NjZv6sHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NjZv6sH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NjZv6sH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'role' => ['privates', '.errored..service_locator.NjZv6sH.App\\Entity\\Role', NULL, 'Cannot autowire service ".service_locator.NjZv6sH": it needs an instance of "App\\Entity\\Role" but this type has been excluded in "config/services.yaml".'],
        ], [
            'role' => 'App\\Entity\\Role',
        ]);
    }
}
