<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LpTJlK5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LpTJlK5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LpTJlK5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'plannigRepository' => ['privates', 'App\\Repository\\PlannigRepository', 'getPlannigRepositoryService', true],
        ], [
            'plannigRepository' => 'App\\Repository\\PlannigRepository',
        ]);
    }
}
