<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G4IdwNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g4IdwN_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g4IdwN_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'plannig' => ['privates', '.errored..service_locator.g4IdwN_.App\\Entity\\Plannig', NULL, 'Cannot autowire service ".service_locator.g4IdwN_": it needs an instance of "App\\Entity\\Plannig" but this type has been excluded in "config/services.yaml".'],
        ], [
            'plannig' => 'App\\Entity\\Plannig',
        ]);
    }
}
