<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MdRzbTjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mdRzbTj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mdRzbTj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandesBoutique' => ['privates', '.errored..service_locator.mdRzbTj.App\\Entity\\CommandesBoutique', NULL, 'Cannot autowire service ".service_locator.mdRzbTj": it needs an instance of "App\\Entity\\CommandesBoutique" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commandesBoutique' => 'App\\Entity\\CommandesBoutique',
            'entityManager' => '?',
        ]);
    }
}
