<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__DhLCXqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..dhLCXq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..dhLCXq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phase' => ['privates', '.errored..service_locator..dhLCXq.App\\Entity\\Phase', NULL, 'Cannot autowire service ".service_locator..dhLCXq": it needs an instance of "App\\Entity\\Phase" but this type has been excluded in "config/services.yaml".'],
        ], [
            'phase' => 'App\\Entity\\Phase',
        ]);
    }
}
