<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitsBoutique2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VLYgdnA.App\Entity\ProduitsBoutique' shared service.
     *
     * @return \App\Entity\ProduitsBoutique
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VLYgdnA": it needs an instance of "App\\Entity\\ProduitsBoutique" but this type has been excluded in "config/services.yaml".');
    }
}
