<?php

namespace ContainerLwU7KrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlannigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.d0a79iM.App\Entity\Plannig' shared service.
     *
     * @return \App\Entity\Plannig
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.d0a79iM": it needs an instance of "App\\Entity\\Plannig" but this type has been excluded in "config/services.yaml".');
    }
}
