<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOuvajbV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOuvajbV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOuvajbV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOuvajbV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOuvajbV\App_KernelDevDebugContainer([
    'container.build_hash' => 'OuvajbV',
    'container.build_id' => '430fa1cf',
    'container.build_time' => 1740866910,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOuvajbV');
