<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqQebyk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqQebyk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqQebyk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqQebyk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIqQebyk\App_KernelDevDebugContainer([
    'container.build_hash' => 'IqQebyk',
    'container.build_id' => '7c168c04',
    'container.build_time' => 1740091245,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqQebyk');
